# Generated by Django 4.0.1 on 2022-03-21 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=250, null=True)),
                ('work_order_description', models.CharField(max_length=250, null=True)),
                ('task_type', models.CharField(choices=[('meter replacement', 'SPU - Meter Replacement'), ('meter audit', 'SPU - Meter Audit'), ('retrofit replacement', 'SPU - Retrofit Replacement'), ('new installation', 'SPU - New Installation')], max_length=250, null=True)),
                ('status', models.CharField(choices=[('QC Accepted', 'QC Accepted'), ('QC Rejected', 'QC Rejected')], default='', max_length=250, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('actual_finish_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('meter_number', models.CharField(default='', max_length=200, null=True)),
                ('account_number', models.CharField(default='', max_length=200, null=True)),
                ('city', models.CharField(default='', max_length=250)),
                ('street_number', models.CharField(max_length=250, null=True)),
                ('suburb', models.CharField(default='', max_length=250)),
                ('unit_no', models.CharField(default='', max_length=250, null=True)),
                ('assigned_to_company', models.CharField(default='ZIBIVAX', max_length=100, null=True)),
                ('organisational_unit', models.CharField(default='Zibivax', max_length=100, null=True)),
                ('work_order_notes', models.CharField(max_length=300, null=True)),
                ('allocated_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='users.employee')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Work_admin', to='users.employee')),
            ],
            options={
                'db_table': 'statboard_tasks',
            },
        ),
        migrations.CreateModel(
            name='Normalisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('before_normalise', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('after_normalisation', models.ImageField(upload_to='')),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
    ]
