# Generated by Django 4.0.1 on 2022-03-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table=None,
        ),
    ]
